### ISSUE TITLE
Choose an appropriate python library to work with Git

### ISSUE THREAD

**Issue by yakutovicha** [aiidalab/aiidalab-home#11]
For the moment I am considering/testing three libraries:

- [Dulwich](https://www.dulwich.io/)
- [GitPython](https://github.com/gitpython-developers/GitPython)
- [pygit2](https://github.com/libgit2/pygit2)

The main criteria for me are the following:

1. Easy to install
2. Easy to use
3. Supported git features
4. Ability to work as a part of a daemon process
5. Active development

**Comment by yakutovicha** [comment]
[**Dulwich**](https://www.dulwich.io/)

1. It is easy to install
`> pip install dulwich`

2. It is pretty easy and straightforward to navigate the local repository:
```
In [1]: from dulwich.repo import Repo

In [2]: repo = Repo('.')

In [3]: ls
aiida/                bin/          examples/    open_source_licenses.txt  setup.json
aiida_core.egg-info/  CHANGELOG.md  LICENSE.txt  pyproject.toml            setup.py
AUTHORS.txt           docs/         MANIFEST.in  README.md                 utils/

In [4]: repo
Out[4]: <Repo at '.'>

In [5]: walker = iter(repo.get_walker())

In [6]: walker
Out[6]: <callable-iterator at 0x7f7460620690>

In [7]: nxt = next(walker)

In [9]: nxt.commit
Out[9]: <Commit 6c525c8b0f59eb890e0aaaff0d18af3940dee434>
```
check if update is available (very durty yet):
```
def git_repo_update_available(local_path, remote_url, repo_name, branch='master'):
    """Check whether there are new updates available at the remote repository."""
    from dulwich.errors import GitProtocolError
    from dulwich.client import HttpGitClient
    from dulwich.repo import Repo
    local_repo = Repo(local_path)
    remote_client = HttpGitClient(remote_url)

    # TODO: if local and remote repositories are different, error is not raised
    remote_refs = remote_client.fetch(repo_name, local_repo)

    remote_id = remote_refs['refs/heads/'+branch]
    if local_repo['refs/heads/'+branch].id == remote_id:
        print("No update available")
    else:
        print("Update available")
```
3. Looks like all basic features (commit, pull, push, fetch etc...) are provided.
4. Provides both local and remote interfaces to git repos, so no problems to run as daemon
5. Dulwich is alive and under [active development](https://github.com/dulwich/dulwich). [Nice documentation](https://www.dulwich.io/docs) is also available.

**Comment by yakutovicha** [comment]
[**GitPython**](https://github.com/gitpython-developers/GitPython)

1. Easy to install: 
`> pip install gitpython`

4. The developers suggest **not to use** it as a daemon process, as it _" ...  is not suited for long-running processes (like daemons) as it tends to leak system resources."_ It is quite an important feature for us, so I would strongly prefer not to use it to avoid additional problems.
5. GitPython is alive and under [active development](https://github.com/gitpython-developers/GitPython). [Documentation](https://gitpython.readthedocs.io/en/stable/index.html) is provided

**Comment by yakutovicha** [comment]
[**pygit2**](https://github.com/libgit2/pygit2)
Is composed of python interface (pygit2) and C-library (libgit2)

1. Installation of pygit2 is the most difficult among 3 other candidates. You first need to download the library, then you need to compile it, and then to install: 

```
> wget https://github.com/libgit2/libgit2/archive/v0.27.0.tar.gz
> tar xzf v0.27.0.tar.gz
> cd libgit2-0.27.0/
> cmake .
> make
> sudo make install
```

Once this procedure is completed, pygit2 can be installed from pip
`> pip install pygit2`

Even though it is not difficult -- in a long run can such a setup can cause unexpected problems/inconvenience in automated update of the apps. It may happen that pygit2 will be updated while libgit2 will remain the same. 
Than to me is quite an important point, so I would prefer to avoid using pygit2 if there are no other clear advantages.

**Comment by yakutovicha** [comment]
Based on those considerations, I would choose Dulwich option. The key features that I like are:
1. Works as git client and git server (unlike GitPython that is not recommended to be used in daemon applications)
2. It is fully written in python, no other dependencies (unlike GitPython or pygit2)
3.  Extremely easy to install (unlike pygit2)

and I do not see any problems with supported git functionality.

@ltalirz  and @giovannipizzi  let me know if you have any other thoughts or suggestions. I will google a bit more just to know what people say, however, for me the choice is quite clear now

**Comment by yakutovicha** [comment]
There is also something called [stgit](https://github.com/ctmarinas/stgit), did not investigate it

**Comment by yakutovicha** [comment]
List of git high-level commands available in dulwich can be found [here](https://www.dulwich.io/apidocs/dulwich.porcelain.html)

**Comment by ltalirz** [comment]
@yakutovicha Thanks for looking into this!
dulwich seems fine, also didn't install any extra dependencies besides urllib3 for me. No objections from me
