### ISSUE TITLE
Providing tool in aiidalab-home for user to apply general changes such as migration.

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-home#132]

**Comment by yakutovicha** [comment]
I would suggest starting building the settings page for the aiidalab home. We can already move there the tools from awb.

**Comment by unkcpz** [comment]
Yes, but I don't have time to work on that before next meeting. Can you open an issue for that and add to roadmap? You mentioned in https://github.com/aiidalab/aiidalab-launch/pull/166 but I didn't notice, sorry.

This issue also relates (or inspired) to/by https://github.com/aiidalab/aiidalab-home/issues/94, the button for migrate.

**Comment by unkcpz** [comment]
I hit a wall after I start. The process_list notebook for sure is what we want to move to aiidalab-home but it usings widgets defined in AWB. The problem comes to do we add AWB as the dependencies of `aiidalab-home`. If we do this is contradict our original goal to move the AWB from the initial stack. Any idea on how to elegantly handle this? @danielhollas @yakutovicha
