### ISSUE TITLE
Show the edge version of an app from the latest commit of the default branch in the pre-release list

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-home#134]
The available version list will fetch the tags of the specified branch of an app. For app developer, they are willing to quickly see the newest change they merge to the default branch without making the release by adding the tag.
It would be helpful if the `edge` version can be list in the version list of version selector widget when the `pre-release` checkbok is ticked. This will allow user to install the edge commit immediatly.

**Comment by yakutovicha** [comment]
I am against this one. It is possible to select multiple branches, so it could be harder than one might think. 

Also, I do not see the need to allow users to install non-released stuff (with no tag). We distinguish releases and pre-releases (`a`, `b`, `rc`). How would we classify the `edge` release? Remember: visuals are for the users, not for the developers.

Maybe, it makes more sense to document that something like the code below is also possible.

```bash
$ aiidalab install aiidalab-mfa-cscs@git+https://github.com/aiidalab/aiidalab-mfa-cscs@main
$ aiidalab install aiidalab-mfa-cscs@git+https://github.com/aiidalab/aiidalab-mfa-cscs@7d7ce4e
```

Despite it can be seen when executing `aiidalab install --help`.

**Comment by danielhollas** [comment]
Yeah, I tend to agree with Sasha. Using a command line to install the latest version is perfectly fine as long as it is documented.

**Comment by unkcpz** [comment]
Okay, just from users point of view they need some way to easy find how to install their app without making release every time. I encounter this when I help people in MarketPlace and they complaint that they need to wait 30 min to see aiidalab registry update and can have the new version installed from the app store. 

I close this one and open a new issue for document how to document well on installing the specific commit.
