### ISSUE TITLE
Hide the pre-release checkbox in app store gallery

### ISSUE THREAD

**Issue by unkcpz** [aiidalab/aiidalab-home#138]
Suggested by @danielhollas,

>  the include pre-releases" toggle may better be hidden. If the user wants a pre-release, they should probably go to the "manage app" page anyway.

I don't fully agree with this, we have this functionality and it benefits for the user when need to keep it here. In essence, AiiDAlab encourages quick development so the pre-release should be common. Let's discuss!

**Comment by danielhollas** [comment]
After some thought I am fine with keeping the check-box as is.
