### ISSUE TITLE
Add a mechanism for custom message in home app (for demo server)

### ISSUE THREAD

**Issue by superstar54** [aiidalab/aiidalab-home#184]
Add demo message (message saying that we are in a demo, how long data is kept, …) in AiiDAlab home (initial page with ‘File manager’ ‘Terminal’ … QEapp logo [Jason and Edan] [copied above]
Make sure the default guide/tutorial is on, in the demo server. [Edan Jason Xing]

**Comment by danielhollas** [comment]
> If this is your first visit, you can get started by submitting a new Quantum ESPRESSO calculation using the buttons below!

To clarify (for the purposes of Edan's PR), this is meant to be displayed in the home app, correct? "buttons below" in this context sounds a bit vague (since users still need to open the QeApp?).

**Comment by edan** [comment]
Hi! I think you have been tagging the wrong Edan. Cool project though!

**Comment by danielhollas** [comment]
Oh no, I am so sorry! This is what happens when one comments on Github late at night. :-)
Thanks for letting me know! :heart_hands:

**Comment by yakutovicha** [comment]
related to #54 ?

**Comment by edan-bainglass** [comment]
> related to #54 ?

Thanks for tagging this @yakutovicha. Indeed, this could be used to cover already the demo-server AND first-time-user notifications. Perhaps we should consider integrating this into the very top of ANY app, including the home app. This will could then truly be a general user-notification system. If we do so, we may want to consider if it should be independent of other top-level warnings, such as bug reports.
