### ISSUE TITLE
Add metadata.json for python requirements

### ISSUE THREAD

**Issue by chrisjsewell** [aiidalab/aiidalab-home#51]
i.e. that the Quantum Mobile can read and "understand" what needs to be installed for the app to work.

I believe the requirements to install into the aiida environment (as opposed to the jupyter one) are:

  - aiidalab==20.11.0b1
  - ipython
  - ipywidgets
  - jinja2
  - markdown
  - traitlets

**Comment by ltalirz** [comment]
setup.cfg was added in 4430491c4773e286a585fb74db18ff22b72265a9

@chrisjsewell I'll open a PR to marvel-nccr.aiidalab to start using the setup.cfg
